version: '3.7'
services:
    db:
        image: mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3306:3306"
        env_file:
            - ./project/.env
    php:
        build: ./php-fpm
        ports:
            - "9000:9001"
        volumes:
            - ./project:/var/www/project:cached
            - ./logs/project:/var/www/project/var/log:cached #symfony
            #- ./logs/project:/var/www/project/storage/logs:cached #laravel
        links:
            - db
        extra_hosts:
            - "docker.host:127.0.0.1"
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        links:
            - php
        volumes:
            - ./build/nginx:/etc/nginx/
            - ./logs/nginx:/var/log/nginx:cached
            - ./project:/var/www/project:cached
    elk:
        image: willdurand/elk
        ports:
            - "81:80"
        volumes:
            - ./elk/logstash:/etc/logstash:cached
            - ./elk/logstash/patterns:/opt/logstash/patterns:cached
            - ./logs/project:/var/www/project/var/log:cached
            - ./logs/nginx:/var/log/nginx:cached
